const mix = require("laravel-mix");

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.scripts("resources/js/scripts.js", "public/js/scripts.js")
    .scripts(["resources/js/scripts.js", "resources/js/components/ajaxify.js", "resources/js/templates/admin/scripts.js"], "public/js/templates/admin/scripts.js")
    .scripts("resources/js/templates/admin/apps/create.js", "public/js/templates/admin/apps/create.js")
    .scripts("resources/js/templates/admin/task/index.js", "public/js/templates/admin/task/index.js")
    .scripts("resources/js/templates/admin/products/edit.js", "public/js/templates/admin/products/edit.js")
    .scripts("resources/js/templates/admin/settings/maintenance.js", "public/js/templates/admin/settings/maintenance.js")
    .scripts(["resources/js/templates/admin/dashboard/index.js", "resources/js/templates/admin/index.js"], "public/js/templates/admin/dashboard/index.js")
    .scripts("resources/js/utilities/ajax.js", "public/js/utilities/ajax.js")
    .scripts("resources/js/templates/admin/users/scripts.js", "public/js/templates/admin/users/scripts.js")
    .scripts("resources/js/templates/admin/users/edit-scripts.js", "public/js/templates/admin/users/edit-scripts.js")
    .scripts(["resources/js/utilities/ajax.js", "resources/js/templates/user/show.js"], "public/js/templates/user/show.js")
    .scripts("resources/js/components/carousel.js", "public/js/components/carousel.js")
    .scripts("resources/js/components/dialog.js", "public/js/components/dialog.js")
    .scripts("resources/js/components/notifications.js", "public/js/components/notifications.js")
    .scripts("resources/js/components/notification-banner.js", "public/js/components/notification-banner.js")
    .scripts("resources/js/components/dialog-box.js", "public/js/components/dialog-box.js")
    .scripts("resources/js/components/alert.js", "public/js/components/alert.js")
    .scripts("resources/js/components/emailValidation.js", "public/js/components/emailValidation.js")
    .scripts("resources/js/components/custom-attribute.js", "public/js/components/custom-attribute.js")
    .scripts("resources/js/components/cookie.js", "public/js/components/cookie.js")
    .scripts("resources/js/components/sidebar-accordion.js", "public/js/components/sidebar-accordion.js")
    .scripts("resources/js/components/multiselect.js", "public/js/components/multiselect.js")
    .scripts("resources/js/components/select.js", "public/js/components/select.js")
    .scripts("resources/js/templates/products/index.js", "public/js/templates/products/index.js")
    .scripts("resources/js/templates/products/show.js", "public/js/templates/products/show.js")
    .scripts("resources/js/templates/bundles/index.js", "public/js/templates/bundles/index.js")
    .scripts("resources/js/templates/auth/register.js", "public/js/templates/auth/register.js")
    .scripts("resources/js/templates/auth/forgot-password.js", "public/js/templates/auth/forgot-password.js")
    .scripts("resources/js/templates/admin/index.js", "public/js/templates/admin/index.js")
    .scripts("resources/js/templates/admin/notifications.js", "public/js/templates/admin/notifications.js")
    .scripts("resources/js/templates/admin/teams/index.js", "public/js/templates/admin/teams/index.js")
    .scripts("resources/js/templates/apps/kyc.js", "public/js/templates/apps/kyc.js")
    .scripts("resources/js/templates/apps/create.js", "public/js/templates/apps/create.js")
    .scripts("resources/js/vendor/stoplight.js", "public/js/vendor/stoplight.js")
    .scripts("resources/js/templates/teams/create.js", "public/js/templates/teams/create.js")
    .scripts("resources/js/templates/teams/update.js", "public/js/templates/teams/update.js")
    .scripts("resources/js/templates/teams/create-update-validation.js", "public/js/templates/teams/create-update-validation.js")
    .scripts("resources/js/templates/teams/index.js", "public/js/templates/teams/index.js")
    .scripts("resources/js/templates/teams/show.js", "public/js/templates/teams/show.js")
    .scripts("resources/js/templates/2fa/index.js", "public/js/templates/2fa/index.js")
    .scripts("resources/js/templates/contact/index.js", "public/js/templates/contact/index.js")
    .scripts(["resources/js/vendor/ckeditor.js", "resources/js/components/ckeditor.js"], "public/js/components/ckeditor.js")
    .copy("resources/js/vendor/ckeditor.js.map", "public/js/components/ckeditor.js.map")
    .copyDirectory("resources/js/vendor/translations", "public/js/components/translations")
    .sass("resources/sass/layouts/admin.scss", "public/css/layouts")
    .sass("resources/sass/layouts/cookie-notice.scss", "public/css/layouts")
    .sass("resources/sass/auth/login.scss", "public/css/auth")
    .sass("resources/sass/auth/register.scss", "public/css/auth")
    .sass("resources/sass/auth/verify.scss", "public/css/auth")
    .sass("resources/sass/auth/forgot-password.scss", "public/css/auth")
    .sass("resources/sass/components/action_tab.scss", "public/css/components")
    .sass("resources/sass/components/footer.scss", "public/css/components")
    .sass("resources/sass/components/carousel.scss", "public/css/components")
    .sass("resources/sass/components/alert.scss", "public/css/components")
    .sass("resources/sass/components/dialog.scss", "public/css/components")
    .sass("resources/sass/components/dialog-box.scss", "public/css/components")
    .sass("resources/sass/components/cookie.scss", "public/css/components")
    .sass("resources/sass/components/custom-attribute.scss", "public/css/components")
    .sass("resources/sass/components/multiselect.scss", "public/css/components")
    .sass("resources/sass/components/contact-form.scss", "public/css/components")
    .sass("resources/sass/components/card.scss", "public/css/components")
    .sass("resources/sass/components/card-link.scss", "public/css/components")
    .sass("resources/sass/components/card-icon.scss", "public/css/components")
    .sass("resources/sass/components/card-product.scss", "public/css/components")
    .sass("resources/sass/components/key-feature.scss", "public/css/components")
    .sass("resources/sass/components/sidebar-accordion.scss", "public/css/components")
    .sass("resources/sass/components/heading.scss", "public/css/components")
    .sass("resources/sass/components/card-search.scss", "public/css/components")
    .sass("resources/sass/components/pricing.scss", "public/css/components")
    .sass("resources/sass/components/checkbox-round.scss", "public/css/components")
    .sass("resources/sass/templates/search.scss", "public/css/templates")
    .sass("resources/sass/templates/admin/search.scss", "public/css/templates/admin")
    .sass("resources/sass/templates/apps/index.scss", "public/css/templates/apps")
    .sass("resources/sass/templates/apps/create.scss", "public/css/templates/apps")
    .sass("resources/sass/templates/apps/kyc.scss", "public/css/templates/apps")
    .sass("resources/sass/templates/faq/index.scss", "public/css/templates/faq")
    .sass("resources/sass/templates/user/show.scss", "public/css/templates/user")
    .sass("resources/sass/templates/products/index.scss", "public/css/templates/products")
    .sass("resources/sass/templates/products/show.scss", "public/css/templates/products")
    .sass("resources/sass/templates/products/category.scss", "public/css/templates/products")
    .sass("resources/sass/templates/bundles/index.scss", "public/css/templates/bundles")
    .sass("resources/sass/templates/bundles/show.scss", "public/css/templates/bundles")
    .sass("resources/sass/templates/contact/index.scss", "public/css/templates/contact")
    .sass("resources/sass/templates/getting-started/index.scss", "public/css/templates/getting-started")
    .sass("resources/sass/templates/getting-started/show.scss", "public/css/templates/getting-started")
    .sass("resources/sass/templates/home.scss", "public/css/templates")
    .sass("resources/sass/templates/admin/edit.scss", "public/css/templates/admin/edit.css")
    .sass("resources/sass/templates/admin/index.scss", "public/css/templates/admin/index.css")
    .sass("resources/sass/templates/admin/users/index.scss", "public/css/templates/admin/users/index.css")
    .sass("resources/sass/templates/admin/products/index.scss", "public/css/templates/admin/products/index.css")
    .sass("resources/sass/templates/admin/products/edit.scss", "public/css/templates/admin/products/edit.css")
    .sass("resources/sass/templates/admin/settings/maintenance.scss", "public/css/templates/admin/settings/maintenance.css")
    .sass("resources/sass/templates/admin/teams/index.scss", "public/css/templates/admin/teams/index.css")
    .sass("resources/sass/templates/teams/create.scss", "public/css/templates/teams/create.css")
    .sass("resources/sass/templates/teams/show.scss", "public/css/templates/teams/show.css")
    .sass("resources/sass/templates/2fa/index.scss", "public/css/templates/2fa/index.css")
    .sass("resources/sass/components/_app.scss", "public/css/components")
    .sass("resources/sass/components/_team_app.scss", "public/css/components")
    .sass("resources/sass/components/notification-admin.scss", "public/css/components")
    .sass("resources/sass/components/_notification-portal.scss", "public/css/components")
    .sass("resources/sass/templates/admin/apps/create.scss", "public/css/templates/admin/apps/create.css")
    .sass("resources/sass/templates/admin/users/edit.scss", "public/css/templates/admin/users/edit.css")
    .sass("resources/sass/templates/admin/dashboard/index.scss", "public/css/templates/admin/dashboard/index.css")
    .sass("resources/sass/components/_app-new.scss", "public/css/components")
    .sass("resources/sass/components/_panel.scss", "public/css/components")
    .sass("resources/sass/components/_accordion.scss", "public/css/components")
    .sass("resources/sass/components/_select.scss", "public/css/components")
    .sass("resources/sass/styles.scss", "public/css")
    .sass("resources/sass/templates/admin/tasks/index.scss", "public/css/templates/admin/tasks/index.css")
    .sass("resources/sass/vendor/stoplight.scss", "public/css/vendor")
    .version();
